#iTransMap
#Copyright 2016 Singh KS
#Licensed under the Apache License, version 2.0 (the "License");
#You may not use this file except in compliance with the License.
#You may obtain a copy of the license at
#http://www.apache.org/licenses/LICENSE-2.0
#Unless required by applicable law or agreed to in writing, software distributed
#under the license is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and limitations under
#the license.

puts  " "
print "* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * **\n"
puts  "*                                                                          *"
print "*                       Welcome to iTransMap	                              *\n"
print "* An interactive ruby program for the extension of incompletely/partially  *\n"
print "* assembled transcripts (generated by de-novo transcriptome assemblers)    *\n"
print "* using whole transcriptome (RNA-Seq) data!                                *\n"
puts  "*                                                                          *"
print "* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * **\n"
puts  " "

puts "Copyright 2016 Singh KS"
puts "Licensed under the Apache License, version 2.0 (the \"License\"); You may not use this file except in compliance with the License. You may obtain a copy of the license at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the license is distributed on an \"AS IS\" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the license"

#use ruby (for program frame work) and shell scripting (for local commands) and awk/sed (for file manipulation)

#Class1 - Database creation
#Database A and Database B (trimming of raw reads for database B)

#Class2 - Querying the database
#Query fasta file manipulation/fetching of reads from the database B
	#Sub Class 1 - Database searches (Blast/Hmmer searches)

#class3 - Iterative Mapping
	#Sub Class2 - iterative improvemnet of mapping using smalt aligner/mapper

#class4 - de-novo assembly followed by scaffolding	

